#!/bin/bash
#
# Copyright (c) 2026 Damian Malczewski
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#

###############################################################################
#
#   An utility script to checking which Java version compiled each submodule
#   of this project.
#
###############################################################################

echo '===================================================='
echo 'Verifying Java version for classes within JAR files.'
echo ''
echo '  problem4j-jackson2 must be 52 (Java 8)'
echo '  problem4j-jackson3 must be 61 (Java 17)'
echo ''
echo 'Note that JAR files must exist (./gradlew build).'
echo ''

echo '===== problem4j-jackson2 ===='
javap \
    -verbose \
    -classpath problem4j-jackson2/build/libs/problem4j-jackson2.jar \
    io.github.problem4j.jackson2.ProblemModule \
    | grep "major version"

echo ''
echo '===== problem4j-jackson3 ====='
javap \
    -verbose \
    -classpath problem4j-jackson3/build/libs/problem4j-jackson3.jar \
    io.github.problem4j.jackson3.ProblemJacksonModule \
    | grep "major version"
