name: Gradle Publish [release]

on:
  push:
    tags:
      - "problem4j-jackson-v[0-9]*.[0-9]*.[0-9]*"
      - "problem4j-jackson-v[0-9]*.[0-9]*.[0-9]*-*"
      - "problem4j-jackson3-v[0-9]*.[0-9]*.[0-9]*"
      - "problem4j-jackson3-v[0-9]*.[0-9]*.[0-9]*-*"

jobs:
  publish:
    name: Publish Release
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: "17"
          distribution: "temurin"

      # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
      # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Determine Module and Version
        id: tag_info
        run: |
          TAG="${GITHUB_REF_NAME}"
          echo "Tag: $TAG"

          if [[ "$TAG" =~ ^(.*)-v([0-9]+\.[0-9]+\.[0-9]+.*)$ ]]; then
            MODULE="${BASH_REMATCH[1]}"
            VERSION="${BASH_REMATCH[2]}"
          else
            echo "::error::unrecognized tag format $TAG"
            exit 1
          fi

          echo "::notice::evaluated module $MODULE version $VERSION"
          echo "module=$MODULE" >> $GITHUB_OUTPUT
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Publish Release
        env:
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          PUBLISHING_USERNAME: ${{ secrets.PUBLISHING_USERNAME }}
          PUBLISHING_PASSWORD: ${{ secrets.PUBLISHING_PASSWORD }}
          GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.parallel=false"
        run: |
          MODULE=${{ steps.tag_info.outputs.module }}
          VERSION=${{ steps.tag_info.outputs.version }}
          echo "::notice::publishing $MODULE version $VERSION"
          ./gradlew -Pversion="$VERSION" -Psign $MODULE:publishAllPublicationsToCentralPortal
